// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace R5._08.Project.Database.Entities;

public partial class Scoreboard
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int? NumberOfGames { get; set; }

    public int? NumberOfWins { get; set; }

    public int? AverageTime { get; set; }
}
